name: Feature Branch CI
run-name: ${{ github.actor }} is testing out continuous integration
on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  jsdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate JSDoc
        run: npm run docs

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: jsdoc-docs
          path: docs/

  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
