name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write          # Needed for semantic-release to push tags
  id-token: write          # Required for OIDC authentication to npm
  packages: write          # Allows publishing to npm (via OIDC)

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Run semantic release
        run: npx semantic-release
    env:
      GH_TOKEN: ${{ secrets.MAIN_DEVOPS }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
