name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Run semantic release
        run: npx semantic-release
    env:
      GH_TOKEN: ${{ secrets.MAIN_DEVOPS }}
